### ISSUE TITLE
如何使用呢

### ISSUE THREAD

**Issue by zhllx** [zhongxintech/generator-web#1]
![default](https://cloud.githubusercontent.com/assets/11225741/21937159/16c81cce-d9f1-11e6-88e8-80ec5a5a0936.png)
为什么界面不一样呢？

**Comment by Anspear** [comment]
你好，请你更新一下版本，修复了若干BUG。

**Comment by Anspear** [comment]
你好，使用说明： 1、依次填写【数据库连接】、【端口号】、【数据库名称】、【用户名】、【密码】等数据库相关配置，并填写相关的【包名路径】，生成的文件头部即对应填写的包名路径。 2、【表名】一栏填入需要生成的表的名称，【模型名】一栏填入您要生成的文件的前缀。表名可多选，可一次生成多个表文件，可增加或者减少。 3、点击【生成并下载】按钮即可生成mybatis相关文件并下载至您本地。

**Comment by Anspear** [comment]
因为本项目力求用最小的容量来实现功能，所以只是一个最基本的web项目，别的什么都没加，spring都没用到，只用了最原始的JSP和servlet。**下载后需手动改为web项目即可使用。**
