### ISSUE TITLE
找不到配置文件；数据库连接失败

### ISSUE THREAD

**Issue by Programmer-ZX** [zhongxintech/generator-web#2]
1.找不到配置文件：
       String config_path = "WEB-INF/classes/runtimecfg/generatorConfig.xml";
       WEB_INF前缺少“/”
2.数据库连接失败
       String connection = "jdbc:mysql://" + param.getConnection() + "/" + param.getDataBase();
        封装时，连接地址没加端口号：port

**Comment by Anspear** [comment]
你好，非常感谢提出问题，已修复BUG并上传，更新即可。

**Comment by ityouknow** [comment]
问题解决
