### ISSUE TITLE
mybatis-generator-local-1.3.3.jar是否有自己改造

### ISSUE THREAD

**Issue by superwen0001** [zhongxintech/generator-web#4]
mybatis-generator-local-1.3.3.jar这个jar是不是被改造过？

**Comment by Anspear** [comment]
你好，这个肯定是我们自己本地改造后上传的jar，主要改动有：
1、优化mybitis配置文件代码结构（空格的缩进、元素与元素之间加空行等 ）。
2、修改namespace的生成规则。
3、修改dao和Entity的命名规则和样式。
4、增加entity注释。
5、优化dao文件方法名字。
6、修改对大对象类型的处理。
7、修改生成文件的编码为“UTF-8”。
等。

**Comment by kiwiflydream** [comment]
这样别人可能会觉得不安全，毕竟是关于数据库的信息

**Comment by ityouknow** [comment]
觉得那块不安全呢？只是根据表结构生产代码和xml，其实没有不安全的任何因素
