### ISSUE TITLE
pom.xml 需要配置将本地jar打进war包 

### ISSUE THREAD

**Issue by ecit2011ccj** [zhongxintech/generator-web#6]
tomcat 发布项目时 会抛 找不到 mybatis-generator-local-1.3.3.jar  的异常 经过排除 确认了是 maven install 时不会将 本地jar包 打进war包  

pom.xml 增加配置如下

<plugin>
            	<groupId>org.apache.maven.plugins</groupId>
            	<artifactId>maven-war-plugin</artifactId>
            	<configuration>
            		<warName>${project.artifactId}</warName>
            		<webResources>
            			<resource>
            				<directory>lib/</directory>
            				<targetPath>WEB-INF/lib</targetPath>
            				<includes>
            					<include>mybatis-generator-local-1.3.3.jar</include>
            				</includes>
            			</resource>
            		</webResources>
            	</configuration>
   </plugin>

**Comment by Anspear** [comment]
非常感谢反馈问题，已修复。
