### ISSUE TITLE
maven install 过程中 抛出 -source 1.3 中不支持泛型   错误: 解析时已到达文件结尾 等错误

### ISSUE THREAD

**Issue by ecit2011ccj** [zhongxintech/generator-web#7]
ide 为eclipse  maven 版本 2.2.1   maven install 过程中出现异常

解决方案 ：pom.xml 中增加配置

<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>

**Comment by Anspear** [comment]
非常感谢反馈问题，已修复。
